version: '3.7'
services:
  db:
    image: postgres:13.4
    networks:
      - whereze
    env_file: .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  
  backend:
    image: annadvoskina/backend:1.0.1
    networks:
      - whereze
    env_file: .env


  tgbot:
    image: annadvoskina/tgbot:1.0.1
    networks:
      - whereze
    env_file: .env

networks:
  whereze:
