version: '3.7'
services:
  db:
    image: postgres:13.4
    networks:
      - whereze
    env_file: .env
    ports:
      - 5432:5432

  backend:
    image: annadvoskina/backend
    networks:
      - whereze
    env_file: .env
    ports:
      - 5000:5000
  
  tgbot:
    image: annadvoskina/tgbot
    networks:
      - whereze
    env_file: .env
    ports:
      - 5001:5001
networks:
  whereze:
